language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
    - DJANGO=1.8
    - DJANGO=1.11
    - DJANGO=2.0
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: 3.5
      env: DJANGO=1.8
install:
    - pip install --upgrade pip
    - pip install tox-travis
    - pip install tox coveralls
script:
    - tox
after_success: coveralls
